import type { Profile, Match, Swipe } from "@/db/schema";

export const mockProfiles: Profile[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    email: "maria.garcia@startup.io",
    name: "María García",
    headline: "CTO & Co-founder @ TechFlow",
    skills: ["React", "Node.js", "AWS", "AI/ML", "Python"],
    experienceYears: 8,
    industry: "SaaS/Tech",
    bio: "Ingeniera de software con pasión por construir productos que escalen. Anteriormente en Mercado Libre y Globant. Busco cofounders técnicos para mi próximo proyecto en FinTech.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "tech",
    preferredIndustries: ["fintech", "ai", "saas"],
    linkedinUrl: "https://linkedin.com/in/mariagarcia",
    githubUrl: "https://github.com/mariagarcia",
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    email: "carlos.mendez@vc.fund",
    name: "Carlos Méndez",
    headline: "Partner @ Latam Ventures",
    skills: ["Fundraising", "Strategy", "M&A", "Board Management"],
    experienceYears: 15,
    industry: "Venture Capital",
    bio: "Inversor enfocado en early-stage startups de LATAM. Ex-banker, ahora ayudo a founders a escalar. Portfolio incluye 3 unicornios.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "networking",
    offering: "capital",
    preferredIndustries: ["fintech", "healthtech", "edtech"],
    linkedinUrl: "https://linkedin.com/in/carlosmendez",
    githubUrl: null,
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    email: "ana.rodriguez@design.co",
    name: "Ana Rodríguez",
    headline: "Head of Product Design @ Rappi",
    skills: ["Figma", "User Research", "Design Systems", "Product Strategy"],
    experienceYears: 6,
    industry: "Design/Product",
    bio: "Diseñadora de producto con experiencia en startups de alto crecimiento. Me apasiona crear experiencias que los usuarios amen. Buscando mi próximo desafío como cofundadora.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "tech",
    preferredIndustries: ["consumer", "marketplace", "fintech"],
    linkedinUrl: "https://linkedin.com/in/anarodriguez",
    githubUrl: null,
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    email: "diego.silva@ai.labs",
    name: "Diego Silva",
    headline: "ML Engineer @ Google",
    skills: ["PyTorch", "TensorFlow", "LLMs", "Computer Vision", "MLOps"],
    experienceYears: 5,
    industry: "AI/ML",
    bio: "Ingeniero de ML trabajando en modelos de lenguaje. PhD en CS de Stanford. Quiero aplicar AI para resolver problemas reales en LATAM.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "tech",
    preferredIndustries: ["ai", "healthtech", "edtech"],
    linkedinUrl: "https://linkedin.com/in/diegosilva",
    githubUrl: "https://github.com/diegosilva",
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    email: "laura.torres@mentor.org",
    name: "Laura Torres",
    headline: "Serial Entrepreneur & Mentor",
    skills: ["Leadership", "Scaling", "Fundraising", "GTM Strategy"],
    experienceYears: 20,
    industry: "Entrepreneurship",
    bio: "Fundé y vendí 2 startups (exit combinado $50M). Ahora dedico mi tiempo a mentorear la próxima generación de founders latinoamericanos.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "networking",
    offering: "connections",
    preferredIndustries: ["saas", "marketplace", "fintech"],
    linkedinUrl: "https://linkedin.com/in/lauratorres",
    githubUrl: null,
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    email: "pedro.vargas@growth.io",
    name: "Pedro Vargas",
    headline: "Growth Lead @ Nubank",
    skills: ["Growth Hacking", "Analytics", "SEO/SEM", "Product-Led Growth"],
    experienceYears: 7,
    industry: "Growth/Marketing",
    bio: "Especialista en growth con track record de escalar productos de 0 a millones de usuarios. Data-driven y obsesionado con métricas.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "business",
    preferredIndustries: ["fintech", "consumer", "saas"],
    linkedinUrl: "https://linkedin.com/in/pedrovargas",
    githubUrl: null,
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    email: "sofia.chen@blockchain.dev",
    name: "Sofía Chen",
    headline: "Blockchain Developer & Consultant",
    skills: ["Solidity", "Web3", "Smart Contracts", "DeFi", "Rust"],
    experienceYears: 4,
    industry: "Crypto/Web3",
    bio: "Desarrolladora blockchain especializada en DeFi. Construí protocolos con $100M+ TVL. Buscando el próximo proyecto que revolucione las finanzas.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "tech",
    preferredIndustries: ["crypto", "fintech", "defi"],
    linkedinUrl: "https://linkedin.com/in/sofiachen",
    githubUrl: "https://github.com/sofiachen",
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    email: "miguel.herrera@health.tech",
    name: "Miguel Herrera",
    headline: "Doctor & HealthTech Founder",
    skills: ["Medicine", "Healthcare", "Telemedicine", "Health Policy"],
    experienceYears: 12,
    industry: "HealthTech",
    bio: "Médico con MBA buscando transformar la salud en LATAM. Mi startup anterior conectó 50K pacientes con doctores. Listo para el siguiente capítulo.",
    avatarUrl: null,
    pdfUrl: null,
    lookingFor: "cofounder",
    offering: "business",
    preferredIndustries: ["healthtech", "biotech", "insurance"],
    linkedinUrl: "https://linkedin.com/in/miguelherrera",
    githubUrl: null,
    isActive: true,
    onboardingCompleted: true,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
];

// Demo user (the logged in user for testing)
export const mockCurrentUser: Profile = {
  id: "550e8400-e29b-41d4-a716-446655440000",
  email: "demo@hackaton.app",
  name: "Demo User",
  headline: "Full-Stack Developer & Entrepreneur",
  skills: ["TypeScript", "React", "Next.js", "PostgreSQL", "AI"],
  experienceYears: 5,
  industry: "Tech",
  bio: "Desarrollador full-stack con experiencia en startups. Apasionado por crear productos innovadores.",
  avatarUrl: null,
  pdfUrl: null,
  lookingFor: "cofounder",
  offering: "tech",
  preferredIndustries: ["ai", "fintech", "saas"],
  linkedinUrl: "https://linkedin.com/in/demouser",
  githubUrl: "https://github.com/demouser",
  isActive: true,
  onboardingCompleted: true,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
};

export const mockMatches: (Match & { profile: Profile })[] = [
  {
    id: "match-001",
    userA: mockCurrentUser.id,
    userB: mockProfiles[0].id,
    createdAt: new Date("2024-01-16"),
    profile: mockProfiles[0],
  },
  {
    id: "match-002",
    userA: mockProfiles[3].id,
    userB: mockCurrentUser.id,
    createdAt: new Date("2024-01-17"),
    profile: mockProfiles[3],
  },
];

export const mockSwipes: Swipe[] = [
  {
    id: "swipe-001",
    swiperId: mockCurrentUser.id,
    swipedId: mockProfiles[0].id,
    direction: "right",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "swipe-002",
    swiperId: mockProfiles[0].id,
    swipedId: mockCurrentUser.id,
    direction: "right",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "swipe-003",
    swiperId: mockCurrentUser.id,
    swipedId: mockProfiles[3].id,
    direction: "right",
    createdAt: new Date("2024-01-17"),
  },
  {
    id: "swipe-004",
    swiperId: mockProfiles[3].id,
    swipedId: mockCurrentUser.id,
    direction: "right",
    createdAt: new Date("2024-01-17"),
  },
];

// Helper to get profiles excluding already swiped ones
export function getAvailableProfiles(userId: string, swipedIds: string[]): Profile[] {
  return mockProfiles.filter(
    (p) => p.id !== userId && !swipedIds.includes(p.id) && p.onboardingCompleted
  );
}

// Helper to get matches for a user
export function getMatchesForUser(userId: string): (Match & { profile: Profile })[] {
  return mockMatches.filter(
    (m) => m.userA === userId || m.userB === userId
  );
}
